application: tangentstorm-terratri
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: main.py


inbound_services:
- channel_presence
